### ISSUE TITLE
 Todo list [Admin]

### ISSUE THREAD

**Issue by CyrilFreeman** [polewebdev/client-crm-hdm#10]
En tant qu'Admin je souhaiterai avoir une todolist dans le dashboard qui serait séparé en 3 étapes:

- [ ] faire une partie ToDO Avec marqué une tache a faire
- [ ]  faire une partie in progresse Avec marqué une tache a faire
- [ ]  faire une partie finito Avec marqué une tache a faire
